// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Environment variables with fallbacks for development
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://pbndydilyqxqmcxwadvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBibmR5ZGlseXF4cW1jeHdhZHZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNTYyNTgsImV4cCI6MjA3MTgzMjI1OH0.Afugwfiar4xR4Y3bnO8eImOudaQmv9tAqbT23ORHdUA";

// Validate environment variables in production
if (import.meta.env.PROD && (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY)) {
  throw new Error('Missing required Supabase environment variables');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true, // Enable URL session detection for OAuth callbacks
    flowType: 'pkce' // Use PKCE flow for better security
  }
});